language: python
python:
  - "2.6"
  - "2.7"

jdk:
  - oraclejdk7

os:
  - linux

before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)/src
- export PATH=$PATH:$(pwd)/bin

install:
  - make apks 
  - python setup.py build
  - python setup.py install

script:
  - ./bin/drozer
