language: python
python:
  - "2.6"
  - "2.7"

os:
  - linux
  - osx

before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)/src
- export PATH=$PATH:$(pwd)/bin

install: 
  - python setup.py build
  - python setup.py install

script:
  - ./bin/drozer
